Patch CI pipeline

diff --git a/internal/apps/user/Makefile b/internal/apps/user/Makefile
--- a/internal/apps/user/Makefile
+++ b/internal/apps/user/Makefile
@@ -1,3 +1,12 @@
+.PHONY: build
+build:
+	@if [ -z "$(GOOS)" ] || [ -z "$(GOARCH)" ]; then \
+		echo "Error: GOOS and GOARCH must be set"; \
+		exit 1; \
+	fi
+	@BINARY_NAME=kgym-user-service-$(GOOS)-$(GOARCH)$(if $(filter windows,$(GOOS)),.exe,) && \
+	CGO_ENABLED=0 GOOS=$(GOOS) GOARCH=$(GOARCH) go build -o $$BINARY_NAME ./cmd/main.go
+
 .PHONY: test
 test:
 	gotestsum --format short-verbose -- ./internal/... ./migrations/...
